- name: cart configure
  hosts: cart
  become: yes
  tasks: 
  - name: install catalague
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs 
      state: present

  - name: create a cart
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "roboshop system cart"

  - name: delete the folder
    ansible.builtin.file:
      path: /app
      state: absent

  - name: Create a basic directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: delete cart zip file
    ansible.builtin.file:
      path: /tmp/cart.zip
      state: absent

  - name: ansible download file
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
      dest: /tmp/cart.zip
      
  - name: ansible unzip the file
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

  - name: install npm dependances
    community.general.npm:
      path: /app

  - name: copy the service file
    ansible.builtin.template:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: demon reload
    ansible.builtin.systemd_service:
      daemon_reload: true
 

  - name: start cart
    ansible.builtin.service:
      name: cart
      state: restarted
      enabled: yes