- name: config payment
  hosts: payment
  become: yes
  tasks:
  - name: install python 
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
      - python3
      - gcc 
      - python3-devel    


  - name: create a payment
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "roboshop system payment"

  - name: delete the folder
    ansible.builtin.file:
      path: /app
      state: absent

  - name: Create a basic directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: delete payment zip file
    ansible.builtin.file:
      path: /tmp/payment.zip
      state: absent

  - name: ansible download file
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip
      dest: /tmp/payment.zip
      
  - name: ansible unzip the file
    ansible.builtin.unarchive:
      src: /tmp/payment.zip
      dest: /app
      remote_src: yes

  - name: install dependencie
    ansible.builtin.pip:
      requirements: requirements.txt
      executable: pip3.9
    args:
      chdir: /app

  - name: copy payment service
    ansible.builtin.template:
      src: payment.service
      dest: /etc/sysytemd/system/payment.service

  - name: deamon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start and enable
    ansible.builtin.service:
      - name: payment
        state: restart
        enabled: yes