# ansible-playbook -i localhost, -e '{"instances":["frontend","redis","user","cart","mysql","shipping","rabbitmq","payment"]}'

- name: launch instance
  hosts: all
  connection: local
  vars:
    SD_ID: "sg-0f7364ef02abff9ad"
    AMI_ID: "ami-0220d79f3f480ecf5"
    env: Dev
    action: create
    domain: thoshi.online
    instance:
      - mongodb
      - catalogue
  tasks:
  - name: create instances
    amazon.aws.ec2_instance:
      instance_type: t3.micro
      image_id: "{{ AMI_ID }}"
      security_group: "{{ SD_ID }}"
      name: "{{ item }} - {{ env}}"

      tags:
        project: roboshop
        component: "{{ item }}"
        environment: "{{ env }}"
        name: "{{ item }} - {{ env }}" 

    loop: "{{ instance }}"
    register: user_output

  - name: print out out
    ansible.builtin.debug:
      msg: "{{ user_output }}"

  - name: create route 53 records
    amazon.aws.route53:
      state: present
      zone: "{{ domain }}"
      record: "{{ item.item }}-{{ env }}.{{ domain }}" 
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
    loop: "{{ user_output.results }}"

    name: create route 53 records
    amazon.aws.route53:
      state: present
      zone: "{{ domain }}"
      record: "roboshop-{{ env }}.{{ domain }}" 
      type: A
      ttl: 1
      value: "{{item.instances[0].public_ip_address}}"
      wait: true
    loop: "{{ user_output.results }}"
    when: item.item == "frontend"

  - name: delete route 53 records
    amazon.aws.route53:
      state: absent
      zone: "{{ domain }}"
      record: "{{ item }} - {{ env }}.{{ domain }}" 
      type: A
      ttl: 1
    loop: "{{ instance }}"
    when:  action == "destroy" 

  - name: create delete instance
    amazon.aws.ec2_instance:
      state: absent
      waite: false
      name: "{{ item }}-{{ env }}"
    loop: "{{ instance }}"
    when: action == "destroy"  
    